###
@hostname = localhost
@port = 9000
@host = {{hostname}}:{{port}}
@contentType = application/json


###
@baseUrl = http://localhost:9991

###
# @name getTokenReq
@username = sm1
POST {{baseUrl}}/rwx/userId HTTP/1.1
content-type: {{contentType}}

{
    "username": "{{username}}",
    "code": "asdfsfsd",
    "email": "x@x.com",
    "avatar": "http://avatar",
    "debug": "true"
}

### 
# @name createTag
@authToken = {{getTokenReq.response.headers.Authorization}}
POST {{baseUrl}}/tag/add HTTP/1.1
Authorization: {{authToken}}
content-type: {{contentType}}

{
    "name": "http"
}


### 
# @name getUserTag
@authToken = {{getTokenReq.response.headers.Authorization}}
GET {{baseUrl}}/userTag/list HTTP/1.1
Authorization: {{authToken}}

